In [1]:
# 1 Import required libraries and the NeuralNet class

from NeuralNet import NeuralNet
import numpy as np


In [2]:
# 2 Create a neural network and check its initialization


# Define network architecture: 2 input neurons, 3 hidden, 1 output
nn = NeuralNet([2, 3, 1])

# Print results

print("Neural network object created successfully.")
print("Number of layers:", nn.L)
print("Neurons per layer:", nn.n)
print("Activation function:", nn.fact)

Neural network has been initialized
Architecture (neurons per layer): [2, 3, 1]
Activation function used: sigmoid
 Layer 1: w(3, 2), theta(3, 1)
 Layer 2: w(1, 3), theta(1, 1)
Neural network object created successfully.
Number of layers: 3
Neurons per layer: [2, 3, 1]
Activation function: sigmoid


In [3]:
# Show weights and bias matrices


print(" Checking initialized weight (w) and bias (theta) matrices:")

for l in range(nn.L - 1):
    print(f"\n--- Connection {l}: Layer {l} → Layer {l+1} ---")
    print(f"Weights (w[{l}]) shape: {nn.w[l].shape}")
    print(nn.w[l])
    print(f"Biases (theta[{l}]) shape: {nn.theta[l].shape}")
    print(nn.theta[l])


 Checking initialized weight (w) and bias (theta) matrices:

--- Connection 0: Layer 0 → Layer 1 ---
Weights (w[0]) shape: (3, 2)
[[0.33352604 0.99679732]
 [0.3017128  0.48822644]
 [0.87585878 0.72166784]]
Biases (theta[0]) shape: (3, 1)
[[0.55853951]
 [0.18074662]
 [0.33241031]]

--- Connection 1: Layer 1 → Layer 2 ---
Weights (w[1]) shape: (1, 3)
[[0.90941436 0.60369326 0.45772808]]
Biases (theta[1]) shape: (1, 1)
[[0.03396606]]


In [4]:
# 4 Test forward propagation skeleton


# Create a sample input vector with the same size as the input layer (2 neurons)
x = np.array([0.5, 0.2])

# Perform forward propagation
output = nn.forward(x)

print("Forward propagation result:")
print("Input:", x)
print("Network output:", output)

Forward propagation result:
Input: [0.5 0.2]
Network output: [[0.72041172]]


In [7]:
# 5 Run the backpropagation skeleton 


# Define a simple target output
y_target = np.array([1.0])

# Execute the backpropagation skeleton
print("Running backpropagation skeleton...")
nn.backpropagation(x, y_target)

print("Test completed successfully!")

Running backpropagation skeleton...

[Backpropagation skeleton]
Step 1 - Forward pass done.
Step 2 - Compute delta for output layer:
  Δ^(L) = g'(h^(L)) * (ξ^(L) - target)
Step 3 - Backpropagate deltas for hidden layers:
  Δ^(l) = g'(h^(l)) * (w^(l+1).T @ Δ^(l+1))
Step 4 - Compute gradients (δw, δθ) for all layers.
Step 5 - Update weights and thresholds using learning rate and momentum.
  w <- w + δw
  θ <- θ + δθ
Note: This is the test for logical skeleton, not the full implementation yet.
Test completed successfully!
